# Generated by Django 2.1.5 on 2019-02-18 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='chioce_text',
            new_name='choice_text',
        ),
    ]
